all_info = {
	'diabetes' : {
        "Level1" : {
            "Objective" : "In this level you will know some general information about diabetes",
            "Point1" : "Diabetes is a condition that happens when your blood sugar is too high.",
            "Point2" : "It develops when the pancreas doesn\'t make enough(or no) insulin to digest the sugars.",
            "Point3" : "There are multiple types of diabetes - majorly Type1 and Type2 diabetes.",
            "Point4" : "Both Type 1 and Type 2 diabetes can be influenced by genetics, means inherited.",
            "Point5" : "Apart from genetics, a sedentary life, poor diet, excessive body fat can cause diabetes.",
            "Point6" : "Chronic high blood sugar level can cause problems like heart disease, nerve damages and eye issues."
        },
        "Level2" : {
            "Objective": "In this level you will know about \"Type 2 Diabetes\" - Most Common Type",
            "Point1" : "This is the most common type of diabetes, where the body doesn't make enough insulin.",
            "Point2" : "This mainly affects adults. The body cells don't respond to insulin.",
            "Point3" : "Without treatment - it can cause heart disease, kidney diesease and stroke.",
            "Point4" : "Risk Factors for Type2 diabetes : Overweight, Obese, High BP, High Cholestrol.",
            "Point5" : "Management - More exercises, Eat variety of nutritious food, Blood sugar monitoring.",
            "Point6" : "With lifestyle changes this disease can be reversed to a large extent.",
        },
        "Level3" : {
            "Objective" : "In this level you will know about \"Type1 diabetes\"",
            "Point1" : "It is chronic(life-long) disease that prevents your pancreas from making insulin.",
            "Point2" : "It needs dialy management with synthetic insulin injections and blood sugar monitoring.",
            "Point3" : "Anyone at can develop this, but the ages 4 to 6 and in early puberty are at more risk.",
            "Point4" : "Symptoms are Fatigue, Excessive hunger & thirst, Frequent urination and blurred vision.",
            "Point5" : "Untreated Type1 diabetes can be life-threatening and can be diagonised with Blood glucose test.",
            "Point6" : "It is not caused by eating too much sugar, as Type1 diabetes is an autoimmune condition.",
        },
        "Level4" : {
            "Objective" : "In this level you will learn about the Diagnosis and Tests for diabetes.",
            "Point1" : "For Diagnosis you can take a Fasting Blood glucose test which indicates  your blood sugar levels.",
            "Point2" : "For this test, you don't eat or drink anything except water for at least eight hours before the test.",
            "Point3" : "The food can greatly affect the blood sugar, and the test aims to see the baseline blood sugar levels.",
            "Point4" : "The sugar levels less than 100(mg/dL) are normal; 100 to 125 indicate prediabetes.",
            "Point5" : "The sugar levels above 126(mg/dL) indicates diabetes. Several other checks determine its type.",
            "Point6" : "Chronic high blood sugar levels can cause severe irreverisble complications like shortening of lifespan.",
        },
        "Level5" : {
            "Objective" : "In this level you will learn about the Management and Treatment of diabetes.",
            "Point1" : "Meal planning and choosing a healthy diet greatly impacts the blood sugar levels.",
            "Point2" : "If you take insulin, then counting carbs in the foods and drinks is a large part of management.",
            "Point3" : "Physical activity increases insulin sensitivity and helps reduce insulin resistance.",
            "Point4" : "It is crucial to limit alcohol intake or avoid it and quit smoking for the medications to work.",
            "Point5" : "Getting adequate sleep, of typically 7-9 hours or seek treatment for sleep disorders.",
            "Point6" : "Take medications as directed to manage existing risk factors for heart disease."
        }
    },
    'aids' : {
        "Level1" : {
            "Objective" :"In this level you will know about HIV",
            "Point1" :"HIV stands for human autoimmunodeficiency virus.",
            "Point2" :"HIV infects white blood cells of your immune system causing your white blood cell count to drop.",
            "Point3" :"HIV is called a retrovirus, since it works backward to insert its instructions into your DNA.",
            "Point4" :"Initially, HIV makes you feel sick with flu-like symptoms,thereby hiding noticeable symptoms.",
            "Point5" :"HIV is spread by body fluids like sperms and vaginal fluid and not by hugs, kisses.",
            "Point6" :"When you begin to get certain illnesses that healthy people don't get, HIV has progressed to AIDS."
        },
        "Level2" : {
            "Objective" :"In this level you will know about AIDS",
            "Point1" :"AIDS stands for acquired immunodeficiency syndrome.",
            "Point2" :"AIDS is the final and most serious stage of an HIV infection.",
            "Point3" :"People with AIDS have very low counts of white blood cells and severely damaged immune systems.",
            "Point4" :"If you don't have HIV, you won't get AIDS. With HIV, treatment might help you not get AIDS at all.",
            "Point5" :"Without treatment, almost all people living with HIV will advance to AIDS.",
            "Point6" :"AIDS can cause rapid weight loss, tiredness, ulcers, fevers, night sweats and skin decoloration."
        },
        "Level3" : {
            "Objective" :"In this level you will know about symptoms:",
            "Point1" :"The disease spreads more easily in the first few months after a person is infected.",
            "Point2" :"Initially, symptoms include influenza-like fever, headache, rash and sore throat.",
            "Point3" :"Then, there is asymptomatic stage with not visible or noticeable symptons.",
            "Point4" :"Symptoms now get visible like weight loss, chronic diarrhea, swolen lymph glands,etc.",
            "Point5" :"Due to severe damage to the immune system, the last stage or AIDS kicks in. ",
            "Point6" :"Without treatment, tuberculosis, meningitis, cancers such as Kaposi's Sarcoma can develop."
        },
        "Level4" : {
            "Objective" :"In this level you will learn about the Diagnosis and Tests for HIV.",
            "Point1" :"For HIV, you can be tested by blood or saliva at your home or a healthcare facility.",
            "Point2" :"There are three types of tests: antigen tests, antibody tests and nucleic acid tests.",
            "Point3" :"HIV treatment includes taking combination of pills by mouth, called antiretroviral therapy (ART).",
            "Point4" :"ARTs goal is to reduce HIV level to an extent so as to reduce its weakening effect on immune system.",
            "Point5" :"Time between exposure and when it becomes detectable is called window period. ",
            "Point6" :"Side-effects of ART vary and may include nausea, headache and dizziness, which are temporary."
        },
        "Level5" : {
            "Objective" : "In this level you will learn about the Prevention and Management of HIV.",
            "Point1" : "Having sex without a condom and sharing needles to take drugs are the most common ways that HIV spreads.",
            "Point2" : "Use latex condoms instead of condoms made form animal product (like lambskin).",
            "Point3" : "Doctors do suggest medicines like Antiretroviral drugs (ARVs) to help prevent HIV.",
            "Point4" : "Pre-exposure Prophylaxis(PrEP) is a pill to take everyday if you don't have HIV but are at high risk .",
            "Point5" : "If exposed to HIV, you should contact your healthcare provider about post-exposure Prophylaxis (PEP).",
            "Point6" : "Take medications as directed to manage existing risk factors for HIV as recommended by your healthcare."
        }
    },
    'heartattack':{
        "Level1" : {
            "Objective" : "In this level you will know about Heart Attack",
            "Point1" : "A heart attack is a condition resulting because of restricted blood flow to your heart muscle.",
            "Point2" : "It generally occurs due to blockage in one or many heart's arteries.",
            "Point3" : "Due to lack of blood flow, pumping of blood to body is disrupted, leading to death if not treated.",
            "Point4" : "The blockage is usually due to a buildup of fat, cholestrol-containing deposists called plaques.",
            "Point5" : "If a plaque ruptures, a blood clot is formed causing a attack and killing tissue in heart muscle.",
            "Point6" : "Heart attack is very commonly due to coronary artery disease and is cause of most deaths."
        },
        "Level2" : {
            "Objective" : "In this level you will know about Cardiac Arrest.",
            "Point1" : "Sudden Cardiac Arrest is the sudden loss of all heart activity due to irregular heart rhythm.",
            "Point2" : "Without immediate treatment, sudden cardiac arrest can lead to death.",
            "Point3" : "Sudden cardiac arrest isn't the same as a heart attack.Sudden cardiac arrest is not due to blockage.",
            "Point4" : "Emergency treatment include CPR and shocks to the heart with automated external defibrillator (AED).",
            "Point5" : "Sudden cardiac arrest can happen in people with and without heart diseases. ",
            "Point6" : "Abnormal heart rhythms (arrhthymias) cause most sudden cardiac arrests."
        },
        "Level3" : {
            "Objective" : "In this level you will know about symptoms and signs of heart attack.",
            "Point1" : "Symptoms include chest pain, troubled breathing, insomnia, nausea, dizziness.",
            "Point2" : "People assigned male at birth have different symptoms than those assigned female.",
            "Point3" : "Females are gonna feel less chest pain or discomfort and more fatigue and insomnia.",
            "Point4" : "Sometimes, the first symptom sign of a heart attack is sudden cardiac arrest.",
            "Point5" : "Symptoms of cardiac arrest include heart attack, chest pain, fainting, brugada syndrome.",
            "Point6" : "Cardiac Arrest can result due to heart valve disease, cardiomyopathy, history of fainting."
        },
        "Level4" : {
            "Objective" : "In this level you will learn about the Diagnosis and Tests for Heart Attack.",
            "Point1" : "For diagnosis, if you have heart attack symptoms, you should undergo a physical examination.",
            "Point2" : "Many tests are performed like blood tests, ECG, Echocardiogram, Coronary Angiogram, Heart MRI.",
            "Point3" : "An echocardiogram uses sound waves to create an image of the heart's chambers and valves.",
            "Point4" : "MRI test uses powerful magnetic field to create an image of heart which can show the desired problems.",
            "Point5" : "In the case of Cardiac arrests quick diagnosis is required otherwise the consition can be fatal.",
            "Point6" : "A person's symptoms are often the best way to diagnose cardiac arrest if they are unconscious."
        },
        "Level5" : {
            "Objective" : "In this level you will learn about the Management and Treatment of heart attacks.",
            "Point1" : "Treating a heart attack means restoring blood flow to the affected heart muscle as soon as possible.",
            "Point2" : "After attack treatment includes medications for anti-clotting, thrombolytic, anti-arrhthymias.",
            "Point3" : "People having trouble breathing or with low blood oxygen levels often receive supplementary oxygen.",
            "Point4" : "Angioplasty, pacemaker, bypass surgery are the most used treatments and in some cases heart transplant.",
            "Point5" : "Sudden cardiac arrest can be fatal if it lasts longer than eight minutes without CPR. Hence perform CPR.",
            "Point6" : "Use an AED, if available. CPR with defibrillator rescues a person from sudden cardiac arrest."
        },
    },
    'COPD' : {
        "Level1":{
            "Objective" : "In this level you will know about COPD:",
            "Point1" : "COPD is a chronic inflammatory lung disease that causes obstructed airflow from the lungs.",
            "Point2" : "Caused by long-term exposure to irritating gases or particulate matter, often from cigarette smoke.",
            "Point3" : "People with COPD are at increased risk of developing heart disease, lung cancer and other conditions.",
            "Point4" : "COPD is not curable but symptoms can improve if one avoids smoking and exposure to air pollution.",
            "Point5" : "Emphysema and chronic bronchitis are the two most common conditions that contribute to COPD. ",
            "Point6" : "Asthma and COPD are similar in many ways, however COPD is chronic and progressive, unlike Asthma."
        },
        "Level2":{
            "Objective" : "In this level you will know about Chronic Bronchitis and Emphysema:",
            "Point1" :"Chronic bronchitis irritates your bronchial tubes, which carry air to and from your lungs.",
            "Point2" : "In response, the tube swells and mucus builds up along the lining.",
            "Point3" : "Small, hair:like structures called cilia are damaged as a result of chronic bronchitis.",
            "Point4" : "Emphysema is the breakdown of the walls of the tiny air sacs (alveoli) at the end of the bronchial tubes.",
            "Point5" : "The air sacs play a crucial role in transferring oxygen into your blood and carbon dioxide out.",
            "Point6" : "Damage caused by Emphysema to the walls of air sacs makes it hard to get a full breath."
        },
        "Level3":{
            "Objective" : "In this level you will know about symptoms and signs of COPD",
            "Point1" : "COPD symptoms often don't appear until significant lung damage has occurred. ",
            "Point2" : "Symptoms may include shortness of breath, wheezing, chronic cough with mucus, swelling in ankles, feets.",
            "Point3" : "Infected people also experience expisodes like exacerbations during which symptoms become worser. ",
            "Point4" : "Some people with COPD get frequent respiratory infections such as colds and the flu.",
            "Point5" : "COPD and asthma share common symptoms (cough, wheeze and difficulty breathing) and people may have both.",
            "Point6" : "People with COPD have a higher risk for lung infections, cancer, heart problems, depression and anxiety."
        },
        "Level4":{
            "Objective" : "In this level you will learn about the Diagnosis and Tests for COPD.",
            "Point1" : "To assess your lungs, your healthcare provider will take your medical history, perform a physical exam.",
            "Point2" : "Physical Exam includes checking blood pressures, examining ENT, checking for swellings in feets.",
            "Point3" : "Providers use a simple test called spirometry to see how well your lungs work which includes blowing air.",
            "Point4" : "Other tests includes pulse oximetry, chest CT:scan, arterial blood gases and ECGs.",
            "Point5" : "There are 4 stages of COPD, mild COPD with slight breathing difficulty, then moderate to severe COPD. ",
            "Point6" : "The last stage, very severe COPD includes shortness of breath for everything and need suplemental oxygen."
        },
        "Level5":{
            "Objective" : "In this level you will learn about the Management and Treatment of COPD.",
            "Point1" : "COPD isn't curable, but it can get better by not smoking, avoiding air pollution and getting vaccines.",
            "Point2" : "There are several treatments like inhaling medicines, steroid pills, pulmonary rehabilitation and surgery.",
            "Point3" : "Bronchodilator inhalers are the most important medicines as they relax the airways to keep them open.",
            "Point4" : "Lifestyle changes can improve COPD, quit smoking or vaping, protect yourself from lung infections.",
            "Point5" : "Some inhalers open the airways and may be given regularly to prevent or reduce symptoms.",
            "Point6" : "Inhaled corticosteroids are sometimes given in combination with these to reduce inflammation in the lungs."
        },
    },
    'alzheimers':{
        "Level1":{
            "Objective" : "You will know about Alzheimers",
            "Point1" : "Alzheimer's disease causes a decline in memory, thinking, learning and organizing skills over time. ",
            "Point2" : "It's the most common cause of dementia and usually affects people over the age of 65.",
            "Point3" : "There's no cure for Alzheimer's, but certain medications and therapies can help manage symptoms temporarily.",
            "Point4" : "Dementia describes the state of a person's mental function. It's not a specific disease.",
            "Point5" : "A person with dementia has a change in or decline in memory, reasoning, language, behaviour.",
            "Point6" : "At the most severe stage, a person depends completely on others for help with simple daily tasks."
        },
        "Level2":{
            "Objective" : "In this level you will know about Alzerimer and Dementia:",
            "Point1" : "Dementia is a syndrome that can be caused by a number of diseases which over time destroy nerve cells. ",
            "Point2" : "Dementia has physical, psychological, social and economic impacts.",
            "Point3" : "Smoking, physically inactive, high blood pressure and sugar , obesity, depression increase the risk of dementia.",
            "Point4" : "Stages of Alzheimer start from preclinical Alzheimer, then mild cognitive impairment and finally severe dementia.",
            "Point5" : "Alzheimer's disease is common. It affects approximately 24 million people across the world.",
            "Point6" : "In advanced stages, severe loss of brain function can cause dehydration, malnutrition or infection."
        },
        "Level3":{
            "Objective" : "In this level you will know about symptoms and signs of Alzheimer and Dementia",
            "Point1" : "Memory loss is the key symptom of Alzheimer's disease.",
            "Point2" : "Early signs include difficulty remembering recent events or conversations. ",
            "Point3" : "Everyone has memory lapses at times, but the memory loss associated with Alzheimer's disease persists and gets worse.", 
            "Point4" : "Alzheimer's disease causes difficulty concentrating and thinking, especially about abstract concepts such as numbers.",
            "Point5" : "Brain changes that occur in Alzheimer's disease can affect moods and behaviors.",
            "Point6" : "In the final stage of Alzheimer's, the person often becomes vulnerable to infections, especially pneumonia."
        },
        "Level4":{
            "Objective" : "In this level you will learn about the Diagnosis and Tests for Alzheimer and Dementia.",
            "Point1" : "An important part of diagnosing Alzheimer's disease includes being able to explain your symptoms. ",
            "Point2" : "Input from a close family member or friend about the symptoms and their impact on the daily life helps. ",
            "Point3" : "Biomarker tests include specific types of PET scans and tests that measure amyloid and tau proteins in the blood fluid.",
            "Point4" : "Diagnosing Alzheimer's disease would likely include physical and neurological exam, lab tests, neuropsychological testing.",
            "Point5" : "Brain imaging by MRI or CT scan is used to pinpoint visible changes related to conditions other than Alzheimer's disease.",
            "Point6" : "During a PET scan, a low-level radioactive tracer is injected into the blood to reveal a particular feature in the brain."
        },
        "Level5":{
            "Objective" : "In this level you will learn about the Management and Treatment of Alzheimer and Dementia.",
            "Point1" : "There's no cure for Alzheimer's disease, but certain medications can temporarily slow the worsening of dementia symptoms.",
            "Point2" : "Beginning treatment as early as possible for Alzheimer's could help maintain daily functioning for a while.",
            "Point3" : "The FDA has approved two types of drugs to treat Alzheimer's disease: Cholinesterase inhibitors and NMDA antagonists.",
            "Point4" : "The FDA has given accelerated approval for aducanumab, the first disease-modifying therapy for Alzheimer's disease.",
            "Point5" : "Medications that may help in some are antidepressants, anti-anziety drugs, anticonvulsant and antipsychotic drugs.",
            "Point6" : "Memantine is FDA-approved for treating moderate to severe Alzheimer's disease. It helps keep certain brain cells healthier."
        },
    },
    "hepatitis" : {
        "Level1" :{
            "Objective":"In this level you will know about Hepatitis.",
            "Point1" : "Hepatitis is inflammation in your liver. Inflammation is your body’s response to an infection or injury. ",
            "Point2" : "Short-term liver inflammation is called acute hepatitis. It’s an immediate response to an urgent problem.",
            "Point3" : "Long-term liver inflammation is called chronic hepatitis. It’s a continuous response to an ongoing problem.",
            "Point4" : "Having chronic hepatitis B increases your risk of developing liver failure, liver cancer or cirrhosis.",
            "Point5" : "Inflammation works to defend and repair your liver tissues from harm. If severe, it itself can harm your liver.",
            "Point6" : "There are 5 main hepatitis viruses, referred to as types A, B, C, D and E.",
        },
        "Level2" :{
            "Objective":"In this level you will know about Hepatitis A,B,C,D,E",
            "Point1" : "Hepatitis A and E are typically caused by ingestion of contaminated food or water.",
            "Point2" : "Hepatitis B, C and D usually occur as a result of parenteral contact with infected body fluids. ",
            "Point3" : "Hepatitis B and C lead to chronic disease and are the most common cause of liver cirrhosis and cancer.",
            "Point4" : "Most adults with hepatitis B recover fully, even if their symptoms are severe.",
            "Point5" : "Infants and children are more likely to develop a long-lasting hepatitis B infection.",
            "Point6" : "Hepatitis B is passed to person through blood, semen or other body fluids. It does not spread by sneezing or coughing.",
        },
        "Level3" :{
            "Objective":"In this level you will know about symptoms and signs of Hepatitis",
            "Point1" : "Hepatitis can be stealthy. It doesn’t always cause noticeable symptoms at first. ",
            "Point2" : "Symptoms usually appear about 1-4 months after getting infected.",
            "Point3" : "Acute symptoms include upper abdominal pain, nausea, fatigue, fever.",
            "Point4" : "Additional symptoms may occur if hepatitis begins to interfere with your liver functioning.",
            "Point5" : "When liver isn't able to process bile and it has no where to go and it overflows the bloodstream.",
            "Point6" : "Additional symptoms include jaundice, pruritus (itchy skin), drowsiness, dark pee and light stool.",
        },
        "Level4" :{
            "Objective":"In this level you will learn about the Diagnosis and Tests for Hepatitis",
            "Point1" : "Hepatitis can be diagnosed with liver function tests, imaging tests and liver biopsy. ",
            "Point2" : "Liver function tests are blood tests that measure different substances in your blood that your liver produces.",
            "Point3" : "Imaging tests of your liver can show swelling from hepatitis and issues affecting the bile ducts or blood vessels.",
            "Point4" : "A liver biopsy is a minor procedure to take a small tissue sample from your liver to test in a lab.",
            "Point5" : "Physical examination, ultrasound, fibroscan can also be performed to assess degree of liver fibrosis and scarring.",
            "Point6" : "An abdominal ultrasound can reveal fluid in abdomen, liver damage, liver tumors.",
        },
        "Level5" :{
            "Objective":"In this level you will learn about the Management and Treatment of Hepatitis.",
            "Point1" : "Healthcare providers treat hepatitis by removing as many stress factors from your liver as they can.",
            "Point2" : "Some people might benefit from medications to help manage their blood lipids (fat in your blood) or blood sugar.",
            "Point3" : "Chronic hepatitis C is curable with antivirals, while chronic hepatitis B will need lifelong treatment.",
            "Point4" : "Medications and lifestyle changes can reduce the stress on your liver and limit the severity of chronic hepatitis. ",
            "Point5" : "Getting injected with immunoglobulin (antibody) within 24 hours of exposure to virus may help preventing Hepatitis.",
            "Point6" : "Hepatitis can be prevented by getting vaccinated, maintain good hygiene, maintaning blood sugar and fat.",
        },
    },
    "menstrual" : {
        "Level1" :{
            "Objective":"In this level you will know about Menstrual Hygiene",
            "Point1" : "Menstrual hygiene refers to the practices and measures taken to maintain cleanliness and health during menstruation.",
            "Point2" : "Good menstrual health and hygiene can prevent infections, reduce odors, and help you stay comfortable during periods.",
            "Point3" : "You can choose many types of menstrual products to absorb or collect blood during your period.",
            "Point4" : "Sanitary pads, tampons, menstrual cups, menstrual discs, and period underwear are commonly used.",
            "Point5" : "Menstrual hygiene includes education and awareness about menstruation, promoting healthy practices.",
            "Point6" : "Each year on May 28, Menstrual Hygiene Day is observed to highlight good menstrual hygiene practices.",
        },
        "Level2" :{
            "Objective":"In this level you will learn about Menstrual Hygiene practices",
            "Point1" : "Regular changing of sanitary products, typically every 4-6 hours, to prevent bacterial growth and odor.",
            "Point2" : "Avoidance of harmful practices like using unclean materials (e.g., rags, leaves) as makeshift sanitary products.",
            "Point3" : "Wash the outside of your vagina (vulva) and bottom every day and avoid soap as vagina is self-cleaning organ.",
            "Point4" : "Wash your hands before and after using the restroom and before using a menstrual product.",
            "Point5" : "Poor menstrual hygiene practices can contribute to vagina infection, UTI, reproductive tract infections. ",
            "Point6" : "Drink enough liquids. This can help wash out urinary tract infections (UTIs) and help prevent infections.",
        },
        "Level3" :{
            "Objective":"In this level you will know about symptoms and signs of Poor Menstrual Hygiene ",
            "Point1" : "Accumulation of bacteria and blood, lead to a foul odor emanating from the genital area.",
            "Point2" : "Prolonged contact with damp sanitary products can cause skin irritation, redness, itching, rashes in the genital area.",
            "Point3" : "Individuals experiencing poor menstrual hygiene may feel socially isolated due to odor or visible stains on cloths.",
            "Point4" : "Bacterial or yeast infections may occur when menstrual blood is not adequately absorbed or by using unclean products.",
            "Point5" : "Using Scented hygiene products can irritate the skin and impact your natural pH balance.",
            "Point6" : "Tight fabrics can trap moisture and heat, allowing germs to thrive. Wear lightweight, breathable clothes.",
        },
        "Level4" :{
            "Objective":"In this level you will learn about the Diagnosis and Tests for Menstrual Health",
            "Point1" : "A pelvic exam may be conducted to assess the reproductive organs for any abnormalities, which affect menstrual health.",
            "Point2" : "Hormone levels may be measured through blood tests to evaluate thyroid function assess levels of reproductive hormones.",
            "Point3" : "Pelvic ultrasound uses sound waves to create images of the pelvic organs, helping to diagnose conditions such as cyst.",
            "Point4" : "In endometrial biopsy a sample of tissue from the lining of the uterus is collected and examined under a microscope.",
            "Point5" : "Laparoscopy to visually inspect the pelvic organs and diagnose conditions like endometriosis.",
            "Point6" : "An annual well-woman exam is a full check-up that includes a pap smear, a pelvic exam, and a breast exam. ",
        },
        "Level5" :{
            "Objective":"In this level you will learn about the Management and Treatment of Menstrual Health.",
            "Point1" : "Lifestyle modifications including regular exercise, stress management techniques, and a balanced diet.",
            "Point2" : "Iron supplements to prevent or treat anemia caused by heavy menstrual bleeding.",
            "Point3" : "Surgical interventions like laparoscopic surgery to remove endometrial tissue in cases of severe endometriosis.",
            "Point4" : "Hormonal medications like oral contraceptives to regulate menstrual cycles and manage symptoms of PMS, PCOS. ",
            "Point5" : "Education and counseling to empower individuals with knowledge about menstrual health and hygiene.",
            "Point6" : "Talk to a doctor if you experience a change in odor, have extreme pain, or have more severe period symptoms than usual.",
        },
    },
    "breastcancer" : {
        "Level1" :{
            "Objective":" In this level you will know about Breast Cancer",
            "Point1" : " Breast cancer is one of the most common cancers that affects women and people assigned female at birth (AFAB).",
            "Point2" : "It happens when cancerous cells in your breasts multiply and become tumors.",
            "Point3" : "About 80'%' of breast cancer cases are invasive, meaning a tumor may spread from your breast to other areas of your body.",
            "Point4" : "Breast cancer typically affects women age 50 and older, but it can also affect women and people AFAB who are younger.",
            "Point5" : "Men and people assigned male at birth (AMAB) may also develop breast cancer. ",
            "Point6" : "In 2022, there were 2.3 million women diagnosed with breast cancer and 670 000 deaths globally.",
        },
        "Level2" :{
            "Objective":"In this level you will know more about Breast Cancer",
            "Point1" : "Breast cancer can originate in different parts of the breast, including the ducts or lobules.",
            "Point2" : "Common types of breast cancer are IDC, Lobular breast cancer and DCIS.",
            "Point3" : "In IDC(Invasive ductal carcinoma), cancer starts in your milk ducts and spreads to nearby breast tissue.",
            "Point4" : "Lobular breast cancer starts in the milk-producing glands in your breast and often spreads to nearby breast tissue.",
            "Point5" : "Estrogen and progesterone help cancerous cells to grow.",
            "Point6" : "Factors which increase the risk of breast cancer are obesity, alchohol, family history, postmenopausal hormone therapy.",
        },
        "Level3" :{
            "Objective":"In this level you will know about symptoms and signs of Breast cancer",
            "Point1" : "Most people will not experience any symptoms when the cancer is still early.",
            "Point2" : "A breast lump or thickened area of skin that feels different from the surrounding tissue.",
            "Point3" : "Change in the size, shape or appearance of a breast.",
            "Point4" : "A blood-stained or clear fluid discharge from your nipple.",
            "Point5" : "A nipple that looks flattened or turns inward.",
            "Point6" : "Changes to the skin over the breast, such as skin that looks dimpled or looks like an orange peel.",
        },
        "Level4" :{
            "Objective":"In this level you will learn about the Diagnosis and Tests for Breast Cancer",
            "Point1" : "Healthcare providers may do physical examinations or order mammograms to check for signs of breast cancer",
            "Point2" : "To diagnose breast cancer, breast ultrasound, MRI scan, breast biopsy, immunohistochemistry, genetic tests are done.",
            "Point3" : "Healthcare providers use cancer staging systems to plan treatment.",
            "Point4" : "Breast cancer staging depends on factors like breast cancer type, tumor size and location, and whether cancer has spread. ",
            "Point5" : "In stage 0, cancer hasn't spread from breast ducts. In stage 1, cancer cells are present in nearby breast tissue.",
            "Point6" : "In final stage, stage 4, cancer has spread from breast to areas like your bones, lungs, liver and brain.",
        },
        "Level5" :{
            "Objective":"In this level you will learn about the Management and Treatment of Breast Cancer.",
            "Point1" : "Surgery is the primary breast cancer treatment, but healthcare providers may use other treatments.",
            "Point2" : "Breast cancer surgeries include mastectomy, lumpectomy, breast reconstruction.",
            "Point3" : "Common chemotherapy and radiation therapy side effects include fatigue, nausea and vomiting.",
            "Point4" : "Breast cancer surgeries include complications like infection ar surgical site, blood clots, nerve damage, lymphedema.",
            "Point5" : "A mammogram is an X-ray of the breast tissue. Mammograms are commonly used to screen for breast cancer.",
            "Point6" : "In a breast exam, a healthcare professional looks at the breasts. This might include changes in the skin or to the nipple.",
        },
    },
}


all_quiz = {
    "diabetes" : {
        'Level1' : {
            "Question" : "What points from below are correct about diabetes:",
            "Option1" : "1. Diabetes is a condition that occurs when your blood sugar is too low.",
            "Option2" : "2. Chronic high blood sugar levels cause complications such as heart disease.",
            "Option3" : "3. It can affect the eyes, leading to conditions like diabetic retinopathy.",
            "Option4" : "4. Pancreatitis or removal of part or all of the pancreas, can lead to diabetes.",
        },
        'Level2' : {
            "Question" : "What points from below are correct about Type2 diabetes:",
            "Option1": "1. Having Overweight does not increase risk towards diabetes.",
            "Option2": "2. Type2 diabetes happens only by heredity of the same condition.",
            "Option3": "3. During this, you feel more thirsty and hungrier than usual.",
            "Option4": "4. In Type2 diabetes, the pancreas do not produce enough insulin.",
        },
        'Level3' : {
            "Question" : "What points from below are correct about Type1 diabetes:",
            "Option1" : "1. Children at more risk for Type1 diabetes and develop high blood sugar level",
            "Option2" : "2. For Type1 diabetes it is necessary to take synthetic insulin every day.",
            "Option3" : "3. Lifestyle management is no where related to Type1 diabetes at all.",
            "Option4" : "4. Type1 diabetes is caused by excessive intake of sugary foods.",
        },
        'Level4 ': {
            "Question" : "Select the correct answers:",
            "Option1" : "1. A person with blood sugar level of 150(mg/dL) is not a diabetic patient.",
            "Option2" : "2. You can drink or eat anything before your fasting blood sugar test.",
            "Option3" : "3. Your body gets used to chronic high blood sugar levels with time.",
            "Option4" : "4. You can take the fasting blood sugar test at home or in a clinic."
        },
        'Level5' : {
            "Question" : "Select the correct statements:",
            "Option1" : "1. Physical exercise decrease the insulin levels and should be avoided during diabetes.",
            "Option2" : "2. You should consult a doctor if you have symptoms like increased thirst and frequent urination.",
            "Option3" : "3. With proper management, people with diabetes can and should engage in physical activities.",
            "Option4" : "4. Many women with diabetes can have healthy pregnancies and deliver healthy babies."
        }
    },
    "aids" :{
        "Level1" :{
            "Question" : "Q. What points from below are correct about HIV?",
            "Option1":"1. HIV stands for hetero-immunodeficiency virus.",
            "Option2":"2. HIV is called a retro virus, since it works backwards.",
            "Option3":"3. HIV infects red blood cells of your immune system causing your red blood cell count to drop.",
            "Option4":"4. HIV can spread by sharing food with an infected person.",
        },
        "Level2" :{
            "Question" :"Q. What points from below are correct about AIDS?",
            "Option1" :"1. AIDS stands for auto immunodeficiency syndrome.",
            "Option2" :"2. AIDS is curable and can be completely prevented by treatment.",
            "Option3" :"3. AIDS is a virus which causes HIV infection.",
            "Option4" :"4. AIDS may cause unintended weight loss, mouth and genital ulcers.",
        },
        "Level3" :{
            "Question" : "What points from below are correct about symptoms of HIV/AIDS?",
            "Option1" : "1. Those not infected with HIV, might still get infected with AIDS.",
            "Option2" : "2. Initial symptoms include night sweats, swollen lymph nodes, diarrhea.",
            "Option3" : "3. After getting infected, the virus does not show major symptoms for a long time.",
            "Option4" : "4. Once infected with AIDS, you will certainly develop cancer complications.",
        },
        "Level4" :{
            "Question" : "Select the correct answers?",
            "Option1" : "1. Tests for HIV include taking a single pill everyday by mouth called ART.",
            "Option2" : "2. ART helps in curing and completely eliminating HIV.",
            "Option3" : "3. Testing of HIV during window period will likely result in negative result.",
            "Option4" : "4. Instead of HIV virus, HIV antibodies are detected in antibody tests.",
        },
        "Level5" :{
            "Question" : "What are some methods used in managing and treating HIV/AIDS?",
            "Option1" : "1. If you had a sexual partner with HIV in the past, you shouldn't be worried about getting HIV.",
            "Option2" : "2. You can have sex without condoms, as long as you take PEPs or PrEPs everyday.",
            "Option3" : "3. If you have never been exposed to any STI, then no need to test for any in the future.",
            "Option4" : "4. ARVs can prevent passing HIV from mothers to their children.",
        }
    },
    "heartattack" : {
        "Level1":{
            "Question" : "What points from below are correct about Heart attack?",
            "Option1" : "1. Heart Attack is due to physical injury on the heart or its arteries.",
            "Option2" : "2. Heart Attack is a normal condition and no special help is required.",
            "Option3" : "3. Heart Attack is also known as Myocardial Infarction.",
            "Option4" : "4. Heart Attack is also called cardiac arrest.",
        },
        "Level2":{
            "Question" : " What points from below are correct about Cardiac Arrest?",
            "Option1" : "1. If a person suffers sudden chest pain, then wait for emergency services to come help.",
            "Option2" : "2. Cardiac Arrest happens due to heavy blockage of heart arteries.",
            "Option3" : "3. Cardiac Arrest can only happen if you've got any heart diseases.",
            "Option4" : "4. Emergency treatment for cardiac arrest include giving CPR with regular resxue breaths.",
        },
        "Level3":{
            "Question" : "Which of the following is a common symptom of both a heart attack and cardiac arrest?",
            "Option1" : "1. Chest pain or discomfort",
            "Option2" : "2. Numbness or tingling in the extremities",
            "Option3" : "3. Sudden loss of consciousness",
            "Option4" : "4. Difficulty breathing or shortness of breath",
        },
        "Level4":{
            "Question" : "Which of the following statements about diagnosis and tests for heart attack is/are correct?",
            "Option1" : "1. A physical examination is typically conducted if heart attack symptoms are present.",
            "Option2" : "2. Blood tests, ECG, echocardiogram, coronary angiogram, and heart MRI are commonly performed tests for diagnosis.",
            "Option3" : "3. An echocardiogram utilizes magnetic waves to generate an image of the heart's chambers and valves.",
            "Option4" : "4. MRI testing employs a powerful sound waves to produce an image of the heart, revealing potential issues.",
        },
        "Level5":{
            "Question" : "Choose the correct option(s):",
            "Option1" : "1. Defibrillation can restart the person's heart if they haven't received a shock from an AED yet.",
            "Option2" : "2. Treating heart attack means increasing oxygen level of the body.",
            "Option3" : "3. Angioplasty opens the blocked artery by using a balloon or by removing the plaque buildup.",
            "Option4" : "4. Morphine is administered as a pain medication which helps alleviate chest pain.",
        }
    },
    "COPD":{
        "Level1" : {
            "Question" : "What points from below are correct about COPD?",
            "Option1" : "1. COPD stands for Chronic Obstructive Pulmonary Disease.",
            "Option2" : "2. Smoking and air pollution are the most common causes of COPD.",
            "Option3" : "3. COPD is acute disease and completely curable with proper treatment.",
            "Option4" : "4. COPD is an umbrella term for a range of progressive lung diseases.",
        },
        "Level2" : {
            "Question" : "What points from below are correct about Chronic Bronchitis and Emphysema?",
            "Option1" : "1. Chronic Bronchitis damages the walls of air sacs, making harder to breath.",
            "Option2" : "2. Emphysema is caused by allergens.",
            "Option3" : "3. Chronic Bronchitis damages small hair:like structures called cilia.",
            "Option4" : "4. Emphysema causes daily cough and mucus production in the bronchial tubes.",
        },
        "Level3" : {
            "Question" : "What points from below are correct about COPD?",
            "Option1" : "1. As COPD progresses, people find it more difficult to carry out their normal daily activities.",
            "Option2" : "2. Symptoms show up as soon as person gets COPD.",
            "Option3" : "3. A chronic cough that may produce white, green or yellowish mucus is a symptom of COPD.",
            "Option4" : "4. You should consult healthcare provider if unexplained weight loss, blood in mucus, sustained swelling in feets.",
        },
        "Level4" : {
            "Question" : "Select the correct answers?",
            "Option1" : "1. X-ray can show Emphysema and rule out other lung problems or heart failure.",
            "Option2" : "2. CT scans can detect Emphysema and screen lung cancer.",
            "Option3" : "3. Lab tests are used to diagnose COPD to determine the cause of your symptoms.",
            "Option4" : "4. With stage 2 or higher COPD, you also become prone to lung infections like bronchitis and pneunomia.",
        },
        "Level5" : {
            "Question" : "Select the correct answers?",
            "Option1" : "1. Inhalers are used for reducing or preventing some symptoms.",
            "Option2" : "2. Inhaled medicines that open and reduce swelling in the airways are the main treatments.",
            "Option3" : "3. Whatever changes incorporated in lifestyle can't improve COPD once worsen.",
            "Option4" : "4. Antivirals are used to prevent illness caused by virals mainly influenza which is dangerous for people with COPD.",
        },
    },
    "alzheimers" : {
        "Level1" : {
            "Question" : "What points from below are correct about Alzheimer's?",
            "Option1" : "1. Alzheimer is curable.",
            "Option2" : "2. Alzheimer’s disease (AD) is the most common cause of dementia.",
            "Option3" : "3. Dementia and Alzheimer are the same.",
            "Option4" : "4. Dementia limits the daily functioning of the person over time.",
        },
        "Level2" : {
            "Question" : "What points from below are correct about Dementia and Alzheimer?",
            "Option1" : "1. People with AD in the preclinical stage typically have no symptoms (are asymptomatic).",
            "Option2" : "2. Alzheimer's disease causes a decline in the ability to make sensible decisions and judgments.",
            "Option3" : "3. Cause of Alzheimer is failure of muscle proteins to function.",
            "Option4" : "4. Alzheimer causes the brain to swell and brain cells to die.",
        },
        "Level3" : {
            "Question" : " Which of the following is a key symptom of Alzheimer's disease and dementia?",
            "Option1" : "1. Difficulty remembering past events.",
            "Option2" : "2. Enhanced concentration and abstract thinking abilities.",
            "Option3" : "3. Improved memory retention over time.",
            "Option4" : "4. Persistent memory loss, especially regarding recent events or conversations.",
        },
        "Level4" : {
            "Question" : "What are some methods used in diagnosing Alzheimer's disease and dementia?",
            "Option1" : "1. Self-diagnosis based on internet research",
            "Option2" : "2. Physical and neurological exams",
            "Option3" : "3. Astrology readings",
            "Option4" : "4. An MRI is generally preferred to a CT scan to evaluate dementia.",
        },
        "Level5" : {
            "Question" : "What are some methods used in managing and treating Alzheimer's disease and dementia?",
            "Option1" : "1. Meditation and yoga",
            "Option2" : "2. Herbal remedies and supplements",
            "Option3" : "3. Pharmacological interventions such as cholinesterase inhibitors and NMDA antagonists",
            "Option4" : "4. Medicines to control blood pressure and cholesterol can prevent additional damage to the brain",
        },
    },
    "hepatitis" : {
        "Level1":{
            "Question": "What points from below are correct about Hepatitis?",
            "Option1" : "1. Chronic Hepatitis is an immediate response to an urgent problem.",
            "Option2" : "2. Alcoholic Hepatitis is the damage caused to liver due to alcohol.",
            "Option3" : "3. Commonly, Hepatitis virus causes Hepatitis, besides infections and autoimmune diseases.",
            "Option4" : "4. Viral hepatitis is caused by viruses that infect and damage your liver cells and is not contagious.",
        },
        "Level2":{
            "Question": "What points from below are correct about types of Hepatitis?",
            "Option1" : "1. Hepatitis B has a long-lasting effect on adults than children.",
            "Option2" : "2. A vaccine can prevent Hepatitis B.",
            "Option3" : "3. Pregnant mothers with Hepatitis B can pass the virus to their babies during childbirth.",
            "Option4" : "4. Chronic HBV can lead to complications like liver cancer.",
        },
        "Level3":{
            "Question": "Which of the following is correct about Hepatitis?",
            "Option1" : "1. Symptoms develop spontaneously after infection.",
            "Option2" : "2. As the infection goes, hepatitis affects the kidney functioning.",
            "Option3" : "3. General symptoms include nausea, fatigue, joint pain, yellowing of skin.",
            "Option4" : "4. Mother can infect newborn during childbirth.",
        },
        "Level4":{
            "Question": "What are some methods used in diagnosing hepatitis?",
            "Option1" : "1. Physical exams, liver biopsy.",
            "Option2" : "2. Self-diagnosis based on internet research",
            "Option3" : "3. An ultrasound uses ultrasound waves to create image of organs.",
            "Option4" : "4. X-ray and CT scan.",
        },
        "Level5":{
            "Question": "What are some methods used in managing and treating Hepatitis?",
            "Option1" : "1. Antiviral medications.",
            "Option2" : "2. Antibacterial medications.",
            "Option3" : "3. Injecting immunoglobulin.",
            "Option4" : "4. Increasing blood sugar levels.",
        },
    },
    "menstrual":{
        "Level1":{
            "Question":"What does menstrual hygiene primarily focus on?",
            "Option1" :"1. Proper disposal of used sanitary products",
            "Option2" :"2. Prevention of menstrual diseases",
            "Option3" :"3. Maintenance of cleanliness and health during menstruation",
            "Option4" :"4. Promotion of hormonal balance",
        },
        "Level2":{
            "Question":" What is an essential aspect of maintaining menstrual hygiene?",
            "Option1" :"1. Using unclean materials as makeshift sanitary products",
            "Option2" :"2. Regularly changing sanitary products every 4-6 hours",
            "Option3" :"3. Disposing of used sanitary products in an unhygienic manner",
            "Option4" :"4. Avoiding washing the genital area during menstruation",
        },
        "Level3":{
            "Question":"Which of the following is a potential sign of poor menstrual hygiene?",
            "Option1" :"1.  Regularly changing sanitary products",
            "Option2" :"2.  Genital itching or irritation",
            "Option3" :"3.  Disposing of used sanitary products properly",
            "Option4" :"4.  Unpleasant odor in the genital area",
        },
        "Level4":{
            "Question":"Which diagnostic test is commonly used to evaluate the reproductive organs for abnormalities ovarian cysts?",
            "Option1" :"1.  Blood test",
            "Option2" :"2.  Pelvic ultrasound",
            "Option3" :"3.  Endometrial biopsy",
            "Option4" :"4.  Hormonal test",
        },
        "Level5":{
            "Question":"What is a common treatment option for managing heavy menstrual bleeding?",
            "Option1" :"1. Pelvic ultrasound",
            "Option2" :"2. Endometrial biopsy",
            "Option3" :"3. Hormonal medications",
            "Option4" :"4. Blood test",
        },
    },
    "breastcancer":{
        "Level1":{
            "Question":"What points from below are correct about Breast Cance?",
            "Option1" :"1. Breast Cancer happens in women only.",
            "Option2" :"2. Breast Cancer happens due to vast growth of cancerous cells in breasts.",
            "Option3" :"3. It is more prevalent in younger girls.",
            "Option4" :"4. Breast Cancer is one of the rarest diseases.",
        },
        "Level2":{
            "Question":" What points from below are correct about Breast Cancer?",
            "Option1" :"1. In IDC, cancer starts in milk-producing glands and spread to nearby tissues.",
            "Option2" :"2. Hormones like Estrogen and progesterone help reduce the risk of breast cancer.",
            "Option3" :"3. History of radiation exposure increases the risk of breast cancer.",
            "Option4" :"4. Breast cancer occurs in every country in world.",
        },
        "Level3":{
            "Question":"Which of the following is not a common symptom of breast cancer?",
            "Option1" :"1. Lump or mass in the breast or armpit",
            "Option2" :"2. Breast pain or tenderness",
            "Option3" :"3. Changes in the size or shape of the breast",
            "Option4" :"4. Nipple discharge",
        },
        "Level4":{
            "Question":"Which medical test is commonly used to screen for breast cancer in women without symptoms?",
            "Option1" :"1. Pap smear",
            "Option2" :"2. Mammogram",
            "Option3" :"3. Colonoscopy",
            "Option4" :"4. ECG (Electrocardiogram)",
        },
        "Level5":{
            "Question":"Which treatment involves the complete removal of the breast tissue and is often performed for larger tumors?",
            "Option1" :"1. Lumpectomy",
            "Option2" :"2. Radiation therapy",
            "Option3" :"3. Chemotherapy",
            "Option4" :"4. Mastectomy",
        },
    },
}


all_answer = {
    "diabetes" : {
        'Level1' : [False, True, True, True],
        'Level2' : [False, False, True, True],
        'Level3' : [True, True, True, False],
        'Level4' : [True, False, True, False],
        'Level5' : [True, True, True, True]
    },
    "aids":{
        "Level1": [False,True,False,False],
        "Level2": [False,False,False,True],
        "Level3": [False,True,True,False],
        "Level4": [False,False,True,True],
        "Level5": [False,False,False,True],
    },
    "heartattack":{
        "Level1": [False,False,True,False],
        "Level2": [False,False,False,True],
        "Level3": [True,False,False,False],
        "Level4": [True,True,False,False],
        "Level5": [True,False,True,True],
    },
    "COPD":{
        "Level1": [True,True,False,True],
        "Level2": [False,False,True,False],
        "Level3": [True,False,True,True],
        "Level4": [True,True,False,True],
        "Level5": [True,True,False,True],
    },
    "alzheimers":{
        "Level1": [False,True,False,True],
        "Level2": [True,True,False,False],
        "Level3": [False,False,False,True],
        "Level4": [False,True,False,True],
        "Level5": [False,False,True,True],
    },
    "hepatitis":{
        "Level1": [False,True,True,False],
        "Level2": [False,True,True,True],
        "Level3": [False,False,True,True],
        "Level4": [True,False,True,False],
        "Level5": [True,False,True,False],
    },
    "menstrual":{
        "Level1": [False,False,True,False],
        "Level2": [False,True,False,False],
        "Level3": [False,True,False,True],
        "Level4": [True,False,True,False],
        "Level5": [False,True,False,False],
    },
    "breastcancer":{
        "Level1": [False,True,False,False],
        "Level2": [False,False,True,True],
        "Level3": [False,True,False,False],
        "Level4": [False,True,False,False],
        "Level5": [False,False,False,True],
    }
}